global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'dispatcher-api'
    static_configs:
      - targets: ['dispatcher-api:8080']

  - job_name: 'auth-api'
    static_configs:
      - targets: ['auth-api:8080']

  - job_name: 'fine-api'
    static_configs:
      - targets: ['fine-api:8080']

  - job_name: 'traffic-api'
    static_configs:
      - targets: ['traffic-api:8080']
